CREATE TABLE profesori (
                           id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                           nume varchar(255) NOT NULL,
                           CONSTRAINT pk_cluster PRIMARY KEY (id)
);

CREATE TABLE materii (
                         id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         nume varchar(255) NOT NULL,
                         id_profesor int8,
                         CONSTRAINT pk_materii PRIMARY KEY (id)
);

ALTER TABLE materii ADD CONSTRAINT fk_id_profesori FOREIGN KEY (id_profesor) REFERENCES profesori(id);

CREATE TABLE adrese_studenti (
                                 id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                 strada varchar(255) NOT NULL,
                                 numar varchar(255) NOT NULL,
                                 localitate varchar(13),
                                 CONSTRAINT pk_adresa PRIMARY KEY (id)
);

CREATE TABLE studenti (
                          id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                          nume varchar(255) NOT NULL,
                          prenume varchar(255) NOT NULL,
                          id_adresa int8,
                          cnp varchar(13),
                          CONSTRAINT pk_studenti PRIMARY KEY (id),
                          constraint uq_cnp unique (cnp)
);

ALTER TABLE studenti ADD CONSTRAINT fk_id_adresa FOREIGN KEY (id_adresa) REFERENCES adrese_studenti(id);


CREATE TABLE studenti_to_materii (
                                     id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                     id_student int8,
                                     id_materie int8,
                                     CONSTRAINT pk_studenti_to_materii PRIMARY KEY (id)
);
ALTER TABLE studenti_to_materii ADD CONSTRAINT fk_id_student FOREIGN KEY (id_student) REFERENCES studenti(id);
ALTER TABLE studenti_to_materii ADD CONSTRAINT fk_id_materie FOREIGN KEY (id_materie) REFERENCES materii(id);